name: PR Validation

on:
  push:
    branches:
      - "feature/**"
      - "fix/**"
      - "breaking-change/**"
      - "docs/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js and Cache
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          # Use npm for caching, which Turborepo will leverage
          cache: "npm"

      - name: Install Dependencies
        # Use 'npm ci' for faster, more reliable installs in CI
        run: npm ci

      - name: Check for Changeset
        if: startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/fix/') || startsWith(github.ref, 'refs/heads/breaking-change/')
        run: |
          npx changeset status --since=origin/main
          if [ $(npx changeset status --since=origin/main | grep "No changesets found" | wc -l) -eq 1 ]; then
            echo "No changeset found. Please run 'npx changeset add' and commit the file."
            exit 1
          fi

      - name: Run Lint
        # 'turbo run lint' will only lint the packages that have changed
        run: npx turbo run lint

      - name: Run Tests
        # 'turbo run test' assumes you have a 'test' script in your package.json files
        run: npx turbo run test

      - name: Run Build
        # 'turbo run build' will build all packages in the correct order
        run: npx turbo run build
